#!/usr/bin/env bash

# See:
# https://docs.nvidia.com/ngc/ngc-gcp-setup-guide/creating-persistent-ssd-dataset-disks.html#deleting-persistent-ssd-disk

source configuration.sh
source configuration-disk.sh

gcloud compute instances detach-disk $instance_name --disk $disk_name
