#!/usr/bin/env bash

# See: https://cloud.google.com/deep-learning-vm/docs/cli

source configuration.sh

# `--maintenance-policy=TERMINATE` argument -> Setting Instance Availability Policies: https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#terminate_and_optionally_restart
# `--preemptible` argument -> Preemptible Virtual Machines: https://cloud.google.com/preemptible-vms

gcloud compute instances create $instance_name \
    --zone=$zone \
    --image-project=$image_project \
    --image=$image \
    --machine-type=$instance_type \
    --boot-disk-type=$boot_disk_type \
    --boot-disk-size=$boot_disk_size \
    --accelerator="type=$gpu_type,count=1" \
    --maintenance-policy=TERMINATE \
    --preemptible
